export interface ProofScreenshotItem {
  id: string
  studentId: string
  studentName: string
  imageUrl: string
  aspectRatio: 'portrait' | 'square' | 'landscape'
  badgeLabel?: string
  headline?: string
}

// Curated catalog of all 31 authentic student proof screenshots from public/student_feedback/
export const PROOF_SCREENSHOTS_CATALOG: ProofScreenshotItem[] = [
  {
    id: 'siva-01',
    studentId: 'siva-srinivasan',
    studentName: 'Siva Srinivasan',
    imageUrl: '/student_feedback/siva-srinivasan-01.png',
    aspectRatio: 'portrait',
    badgeLabel: '4 Yrs Struggle to Consistency',
    headline: 'Execution & Session Timing Breakthrough',
  },
  {
    id: 'raja-01',
    studentId: 'raja',
    studentName: 'Raja',
    imageUrl: '/student_feedback/raja-01.png',
    aspectRatio: 'portrait',
    badgeLabel: 'Funded Account Live',
    headline: 'Confidence to Clear Funded Accounts',
  },
  {
    id: 'raja-02',
    studentId: 'raja',
    studentName: 'Raja',
    imageUrl: '/student_feedback/raja-02.png',
    aspectRatio: 'portrait',
    badgeLabel: 'Live Account Trading',
    headline: 'Market Characteristics Clarity',
  },
  {
    id: 'keshav-01',
    studentId: 'keshav-kumar',
    studentName: 'Keshav Kumar',
    imageUrl: '/student_feedback/keshav-kumar-01.png',
    aspectRatio: 'portrait',
    badgeLabel: '100% Perfect Classes',
    headline: 'Down to Earth Mentorship',
  },
  {
    id: 'keshav-02',
    studentId: 'keshav-kumar',
    studentName: 'Keshav Kumar',
    imageUrl: '/student_feedback/keshav-kumar-02.png',
    aspectRatio: 'portrait',
    badgeLabel: 'Personal Ideas Shared',
    headline: 'Uncomplicated Learning',
  },
  {
    id: 'shiny-01',
    studentId: 'shiny',
    studentName: 'Shiny',
    imageUrl: '/student_feedback/shiny-01.png',
    aspectRatio: 'portrait',
    badgeLabel: 'Pattern Loss to ICT Solution',
    headline: 'Zero Fear Execution',
  },
  {
    id: 'aadhil-01',
    studentId: 'aadhil',
    studentName: 'Aadhil',
    imageUrl: '/student_feedback/aadhil-01.png',
    aspectRatio: 'portrait',
    badgeLabel: '50K Futures Funded Pass',
    headline: 'Funded Trader Milestone',
  },
  {
    id: 'aadhil-02',
    studentId: 'aadhil',
    studentName: 'Aadhil',
    imageUrl: '/student_feedback/aadhil-02.png',
    aspectRatio: 'portrait',
    badgeLabel: 'Discord Support Active',
    headline: 'Never Need Another Mentor',
  },
  {
    id: 'rajesh-01',
    studentId: 'rajesh',
    studentName: 'Rajesh',
    imageUrl: '/student_feedback/rajesh-01.png',
    aspectRatio: 'portrait',
    badgeLabel: 'Discipline Improved Daily',
    headline: 'Patient Concept Explanations',
  },
  {
    id: 'karthick-01',
    studentId: 'karthick',
    studentName: 'Karthick',
    imageUrl: '/student_feedback/karthick-01.jpeg',
    aspectRatio: 'portrait',
    badgeLabel: 'Transformative Experience',
    headline: 'Mindset, Discipline & CRT',
  },
  {
    id: 'karthick-02',
    studentId: 'karthick',
    studentName: 'Karthick',
    imageUrl: '/student_feedback/karthick-02.jpeg',
    aspectRatio: 'portrait',
    badgeLabel: 'Deep Market Structure',
    headline: 'Clarity and Purpose in Live Charts',
  },
  {
    id: 'vigneshwaran-01',
    studentId: 'vigneshwaran',
    studentName: 'Vigneshwaran',
    imageUrl: '/student_feedback/vigneshwaran-01.jpeg',
    aspectRatio: 'portrait',
    badgeLabel: '15-Day Progression',
    headline: 'No More Blaming Markets',
  },
  {
    id: 'sibi-anand-01',
    studentId: 'sibi-anand',
    studentName: 'Sibi Anand',
    imageUrl: '/student_feedback/sibi-anand-01.jpeg',
    aspectRatio: 'portrait',
    badgeLabel: 'Doubts Cleared Patiently',
    headline: 'Clean Market Understanding',
  },
  {
    id: 'murali-01',
    studentId: 'murali',
    studentName: 'Murali',
    imageUrl: '/student_feedback/murali-01.jpeg',
    aspectRatio: 'portrait',
    badgeLabel: 'Life Transformation Goal',
    headline: 'From Exam Prep to ICT Master',
  },
  {
    id: 'murali-02',
    studentId: 'murali',
    studentName: 'Murali',
    imageUrl: '/student_feedback/murali-02.jpeg',
    aspectRatio: 'square',
    badgeLabel: 'Dedication & Support',
    headline: 'Future Meetup Commitment',
  },
  {
    id: 'navin-01',
    studentId: 'navin',
    studentName: 'Navin',
    imageUrl: '/student_feedback/navin-01.jpeg',
    aspectRatio: 'square',
    badgeLabel: 'Late Night Doubt Support',
    headline: 'Trading Leaders School Professor',
  },
  {
    id: 'vimal-01',
    studentId: 'vimal',
    studentName: 'Vimal',
    imageUrl: '/student_feedback/vimal-01.jpeg',
    aspectRatio: 'portrait',
    badgeLabel: 'Live Error Correction',
    headline: 'Right Guidance & Mentorship',
  },
  {
    id: 'narendra-01',
    studentId: 'narendra',
    studentName: 'Narendra',
    imageUrl: '/student_feedback/narendra-01.jpeg',
    aspectRatio: 'portrait',
    badgeLabel: 'Journaling & Backtesting',
    headline: 'Improvised Syllabus by Heart',
  },
  {
    id: 'aruna-01',
    studentId: 'aruna',
    studentName: 'Aruna',
    imageUrl: '/student_feedback/aruna-01.jpeg',
    aspectRatio: 'square',
    badgeLabel: '10/10 Clarity Rating',
    headline: 'HTF & LTF Proper Execution',
  },
  {
    id: 'gowtham-01',
    studentId: 'gowtham',
    studentName: 'Gowtham',
    imageUrl: '/student_feedback/gowtham-01.jpeg',
    aspectRatio: 'portrait',
    badgeLabel: '4-Digit Payout Achieved',
    headline: 'Lucid Trading Payout Certificate',
  },
  {
    id: 'gowtham-02',
    studentId: 'gowtham',
    studentName: 'Gowtham',
    imageUrl: '/student_feedback/gowtham-02.jpeg',
    aspectRatio: 'landscape',
    badgeLabel: 'Certificate Verified',
    headline: 'Sling Shot Setup Success',
  },
  {
    id: 'vinoth-01',
    studentId: 'vinoth',
    studentName: 'Vinoth',
    imageUrl: '/student_feedback/vinoth-01.jpeg',
    aspectRatio: 'landscape',
    badgeLabel: 'Highest Single-Day Profit',
    headline: 'Credit to Setups & Discipline',
  },
  {
    id: 'dhinesh-k-01',
    studentId: 'dhinesh-k',
    studentName: 'Dhinesh K',
    imageUrl: '/student_feedback/dhinesh-k-01.jpeg',
    aspectRatio: 'portrait',
    badgeLabel: '$814 Payout Certificate',
    headline: 'Lucid Trading Payout Proof',
  },
  {
    id: 'dinesh-01',
    studentId: 'dinesh',
    studentName: 'Dinesh',
    imageUrl: '/student_feedback/dinesh-01.jpeg',
    aspectRatio: 'square',
    badgeLabel: 'Consistent Win Rate',
    headline: 'Unshakeable Psychological Edge',
  },
  {
    id: 'ramki-01',
    studentId: 'ramki',
    studentName: 'Ramki K',
    imageUrl: '/student_feedback/ramki-01.jpeg',
    aspectRatio: 'portrait',
    badgeLabel: 'Phase II Evaluation Passed',
    headline: 'Certificate of Achievement',
  },
  {
    id: 'meiyappan-01',
    studentId: 'meiyappan',
    studentName: 'Meiyappan',
    imageUrl: '/student_feedback/meiyappan-01.jpeg',
    aspectRatio: 'portrait',
    badgeLabel: '$202.71 Phase II Certificate',
    headline: 'Offline Batch Milestone',
  },
  {
    id: 'manoj-k-01',
    studentId: 'manoj-k',
    studentName: 'Manoj K',
    imageUrl: '/student_feedback/manoj-k-01.jpeg',
    aspectRatio: 'portrait',
    badgeLabel: '$74.00 First Payout',
    headline: 'Big Step for Big Turning',
  },
  {
    id: 'kavi-y-01',
    studentId: 'kavi-y',
    studentName: 'Kavi Y',
    imageUrl: '/student_feedback/kavi-y-01.jpeg',
    aspectRatio: 'portrait',
    badgeLabel: 'Level 1 Consistency Cleared',
    headline: 'Prop Firm Milestone Pass',
  },
  {
    id: 'abil-01',
    studentId: 'abil-anjappan',
    studentName: 'Abil Anjappan',
    imageUrl: '/student_feedback/abil-anjappan-01.jpeg',
    aspectRatio: 'square',
    badgeLabel: 'Live Session Execution',
    headline: 'Risk Protocol Mastery',
  },
  {
    id: 'vasantha-01',
    studentId: 'vasanthakumar',
    studentName: 'Vasanthakumar',
    imageUrl: '/student_feedback/vasanthakumar-01.jpeg',
    aspectRatio: 'square',
    badgeLabel: 'Structured Learning Result',
    headline: 'Discipline in Live Markets',
  },
  {
    id: 'xau-01',
    studentId: 'xau-trader',
    studentName: 'XAU Trader',
    imageUrl: '/student_feedback/xau-trader-01.jpeg',
    aspectRatio: 'square',
    badgeLabel: 'Gold Precision Timing',
    headline: 'Dealing Range Strategy Win',
  },
]
